// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBde8-vkgh1Tt3Zo1bWQvQ45shAlQKMihM',
    appId: '1:593236148404:web:f08f70680471afc70a97e1',
    messagingSenderId: '593236148404',
    projectId: 'fitness-workout-planner',
    authDomain: 'fitness-workout-planner.firebaseapp.com',
    storageBucket: 'fitness-workout-planner.appspot.com',
    measurementId: 'G-3HHPRX9MP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6WbBhX2QuG0iJfokSMCgLgayjmY5vrzY',
    appId: '1:593236148404:android:3fe777a05bb344470a97e1',
    messagingSenderId: '593236148404',
    projectId: 'fitness-workout-planner',
    storageBucket: 'fitness-workout-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqPvGcBrG99ypOnJIsANeiEjjXFCXaOM',
    appId: '1:593236148404:ios:b7a5a88c40c566700a97e1',
    messagingSenderId: '593236148404',
    projectId: 'fitness-workout-planner',
    storageBucket: 'fitness-workout-planner.appspot.com',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjqPvGcBrG99ypOnJIsANeiEjjXFCXaOM',
    appId: '1:593236148404:ios:a5737fb180ff7e650a97e1',
    messagingSenderId: '593236148404',
    projectId: 'fitness-workout-planner',
    storageBucket: 'fitness-workout-planner.appspot.com',
    iosBundleId: 'com.example.logintest.RunnerTests',
  );
}
